spring.application.name=API-Gateway
server.port=8080

# Eureka connection
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Gateway route to Authentication
spring.cloud.gateway.routes[0].id=authentication-service
spring.cloud.gateway.routes[0].uri=lb://authentication
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# User Service
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://UserService
spring.cloud.gateway.routes[1].predicates[0]=Path=/user/**

# Admin Service
spring.cloud.gateway.routes[2].id=admin-service
spring.cloud.gateway.routes[2].uri=lb://AdminService
spring.cloud.gateway.routes[2].predicates[0]=Path=/admin/**

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437